-- Tabla para gestionar Banners desde el Gestor Externo
-- Ejecutar en Supabase SQL Editor

create table if not exists content_banners (
  id bigint generated by default as identity primary key,
  title text,
  image_url text not null,
  link_url text, -- Donde lleva al hacer clic
  active boolean default true,
  display_order numeric default 0,
  section text default 'home_slider', -- Por si luego quieres banners en otras zonas
  created_at timestamp with time zone default now()
);

-- Políticas de seguridad (Riesgo bajo si es uso interno, pero bueno tenerlas)
alter table content_banners enable row level security;
create policy "Public read access" on content_banners for select using (true);
create policy "Admin full access" on content_banners for all using (true); -- Simplificado para MVP
