-- Tabla para gestionar Reglas de Descuento desde el Gestor Ecommerce
-- Ejecutar en Supabase SQL Editor

create table if not exists discount_rules (
  id bigint generated by default as identity primary key,
  title text not null,                           -- "LUNES 15% EN POLLO"
  discount_type text default 'percentage',       -- 'percentage' | 'fixed'
  discount_value numeric not null,               -- 15 = 15% o $15
  applies_to text default 'categories',          -- 'all' | 'categories' | 'products'
  applies_to_ids jsonb default '[]'::jsonb,      -- IDs de categorías o SKUs: [12, 45] o ["sku1", "sku2"]
  applies_to_names jsonb default '[]'::jsonb,    -- Nombres para mostrar en UI: ["Pollo", "Carnes"]
  schedule_type text default 'days',             -- 'always' | 'days' | 'date_range'
  schedule_days jsonb default '[]'::jsonb,       -- [1] = Lunes, [2] = Martes ... [0] = Domingo
  date_start date,                               -- Para schedule_type='date_range'
  date_end date,                                 -- Para schedule_type='date_range'
  active boolean default true,
  display_order numeric default 0,
  created_at timestamp with time zone default now()
);

-- Políticas de seguridad
alter table discount_rules enable row level security;
create policy "Public read discount_rules" on discount_rules for select using (true);
create policy "Admin full discount_rules" on discount_rules for all using (true);
